### ISSUE TITLE
Adding items to the list

### ISSUE THREAD

**Issue by Hossman333** [ryanflorence/list-app#2]
If I possibly created a way to add to the list would you consider it?

I'm thinking maybe do something like this:

+
Milk
Eggs
Chicken
Salt

I'll keep it as a single html file too. :)

**Comment by Hossman333** [comment]
instead of clearing the whole list.

**Comment by ryanflorence** [comment]
I was thinking two buttons, one replaces, another appends

**Comment by Hossman333** [comment]
That's an idea. Either way you prefer. 
I really would like to add some things that I don't think you would merge in. Is it against the license to host it on my site??

**Comment by Hossman333** [comment]
I'll give you credit on the bottom.... :)
